<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="OP150_Lsr" Id="{41dcda6c-df8c-48f4-9604-24709f23232f}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM OP150_Lsr
VAR
	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="OP150_Lsr">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>