<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="OP10_SCN_ENB" Id="{49e8c792-f153-4236-b50d-2ccc42448579}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM OP10_SCN_ENB
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="OP10_SCN_ENB">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>