<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="OP10_AUTO" Id="{27eea2b0-764a-4af1-ac23-adcb7c639143}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM OP10_AUTO
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="OP10_AUTO">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>