<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="OP90_CAMERA" Id="{911a2e93-9e04-4a7f-9282-697f696d1304}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM OP90_CAMERA
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[OP90_LH_CMR_OK			:= TRUE;
OP90_RH_CMR_OK			:= TRUE;]]></ST>
    </Implementation>
    <LineIds Name="OP90_CAMERA">
      <LineId Id="3" Count="0" />
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>