<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="OP90_SCN_ENB" Id="{7da84601-3039-4545-87fb-943c88b29f9c}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM OP90_SCN_ENB
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[OP90_HOMING();
OP90_MANUAL();
OP90_AUTO();
]]></ST>
    </Implementation>
    <LineIds Name="OP90_SCN_ENB">
      <LineId Id="3" Count="2" />
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>