<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="MAIN" Id="{362ce905-19b7-4446-9237-c9ceaaf0217a}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	
	test1: BOOL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[test1 := TRUE;
]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>