<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="Laser_Marking" Id="{8db33281-600b-47e0-abaa-d1b44fe04a7e}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM Laser_Marking
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="Laser_Marking">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>